server:
  port: 8089
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/shopapp2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Hoangduy@123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: /api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: syfHZFETm48lXne7m2pPRY7M1XDMK7MTDfO351PbbV0=

logging:
  level:
    org:
      springframework:
        security: DEBUG

vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:4200/payments/payment-callback}"
  tmn-code: "1AFGVYUH" # Add your TMN code here
  secret-key: "45I9OY4MVOJO00CM9TA4S8X773RAKKXB" # Add your secret key here
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

